theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false
color-modes = true
text-width = 100
end-of-line-diagnostics = "hint"
true-color = true
bufferline = 'always'
cursorline = true
rulers = [96]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
center = ["version-control"]
right = ["diagnostics", "selections", "register", "position", "total-line-numbers", "file-encoding"]

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.indent-guides]
render = true
character = "┆"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[keys.normal]
A-x = "extend_to_line_bounds"
A-X = "shrink_to_line_bounds"
x = "select_line_below"
X = "select_line_above"

[keys.select]
A-x = "extend_to_line_bounds"
A-X = "shrink_to_line_bounds"
x = "select_line_below"
X = "select_line_above"
